version: '3'

services:
  base:
    build:
      context: .
      dockerfile: ./base/Dockerfile
    image: ninjaclasher/dmoj-base
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - db_network

  db:
    container_name: iot_mysql
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - ./database/:/var/lib/mysql/
    env_file:
      - ./environment/mysql.env
      - ./environment/mysql-admin.env
    networks:
      - db_network

  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    env_file:
      - ./environment/mqtt.env
    ports:
      - 18083:18083  
    volumes:
      - ./emqx/data:/opt/emqx/data
      - ./emqx/log:/opt/emqx/log
    networks:
      - web_network
      - mqtt_network

  daphne:
    build:
      context: ./daphne
      dockerfile: Dockerfile
    container_name: daphne
    restart: unless-stopped
    volumes:
      - ./repo/:/site/
    working_dir: /site/
    env_file:
      - ./environment/site.env
      - ./environment/mysql.env
      - ./environment/mysql-admin.env
    networks:
      - db_network
      - web_network
      - mqtt_network
    depends_on:
      - db
      - emqx
  celery_worker:
    build:
      context: ./celery_worker
      dockerfile: ./Dockerfile 
    container_name: celery_worker
    restart: unless-stopped
    volumes:
      - ./repo/:/site/
    working_dir: /site/
    env_file:
      - ./environment/site.env
      - ./environment/mysql.env
      - ./environment/mysql-admin.env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    networks:
      - db_network
      - web_network
      - mqtt_network
    depends_on:
      - db
      - emqx

  celery_beat:
    build:
      context: ./celery_beat
      dockerfile: ./Dockerfile  
    container_name: celery_beat
    restart: unless-stopped
    volumes:
      - ./repo/:/site/
    working_dir: /site/
    env_file:
      - ./environment/site.env
      - ./environment/mysql.env
      - ./environment/mysql-admin.env
    networks:
      - db_network
      - web_network
      - mqtt_network
    depends_on:
      - db
      - emqx

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 1883:1883
      - 8883:8883
      - 8083:8083
      - 8084:8084
      - 8888:8888  # NGINX status
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/certs:/etc/nginx/certs
    networks:
      - web_network
      - mqtt_network

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
  mqtt_network:
    driver: bridge
  isolated_network:
    driver: bridge
